workflows:
  ios-capacitor:
    name: iOS Capacitor Build

    environment:
      xcode: latest
      node: latest

    scripts:
      - npm install
      - npx cap sync ios
      - pwd
      - ls
      - ls ios
      - ls ios/App