workflows:
  ios-capacitor:
    name: iOS Capacitor Build

    environment:
      xcode: latest
      node: latest

    scripts:
      - npm install
      - npx cap sync ios
      - cd ios
      - ls
      - cd App
      - ls
      - cd App
      - ls
      - xcodebuild -project App.xcodeproj -scheme App -configuration Release -sdk iphoneos